# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersMeetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeetingLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpapp.Meetings')),
                ('Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpapp.Profile')),
            ],
        ),
    ]
