# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpapp', '0002_usersmeetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='Members',
            field=models.ManyToManyField(to='mpapp.Profile'),
        ),
    ]
