# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mpapp', '0005_auto_20160530_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='Finish',
            field=models.TimeField(default=datetime.datetime(2016, 5, 31, 10, 1, 52, 92143, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
